### ISSUE TITLE
objcopy对elf文件中.bss部分的处理

### ISSUE THREAD

**Issue by ZhengQuancheng** [StevenBaby/onix#1]
您好，objcopy将elf文件转为binary文件时（objcopy -O binary），是不是会将.bss部分填充为0呢？

**Comment by StevenBaby** [comment]
是的，为的就是展开 bss 段，不然需要解析 elf 文件，会稍微麻烦一点

**Comment by ZhengQuancheng** [comment]
我们在用objcopy时，是否要保证binary文件的加载位置与kernel的入口地址一致呢

**Comment by StevenBaby** [comment]
执行 objcopy 的时候是没有地址这个概念的，载入内存的时候才有，由于不是 PIE，所以需要在载入内存的时候，加载到入口地址。

**Comment by ZhengQuancheng** [comment]
![image](https://user-images.githubusercontent.com/60257763/179365521-6e0ce961-e1b1-4cc0-a90c-352cf40ea575.png)
请问system.map的作用是什么呢

**Comment by yinghaoyu** [comment]
system.map是方便调试查看函数入口地址的

**Comment by ZhengQuancheng** [comment]
好的，谢谢你们
