### ISSUE TITLE
请教一下找不到全局变量的问题

### ISSUE THREAD

**Issue by miny1233** [StevenBaby/onix#12]
我自己写了一个内核，用objcopy转成了raw binary，但是如果我使用类似这样的代码：
`printk("hello world");`

或者是其他的全局变量，都是读不出任何数据。
```
char tmp[128] = "ok xdm";
int init()
{
  printk(tmp);
  return 0;
}
```

我反汇编看了一下，发现这些数据都在，只是汇编代码中都访问了错误的地址，有没有什么办法解决呢？

**Comment by StevenBaby** [comment]
建议研究一下数据段具体加载的位置，静态编译试试。

**Comment by miny1233** [comment]
> 建议研究一下数据段具体加载的位置，静态编译试试。

感谢提醒，研究了一下，确实是位置上出了问题，他默认有一个偏移，用Tdata指向0就解决了
