### ISSUE TITLE
疑问：数据类型定义问题

### ISSUE THREAD

**Issue by OpenCreate** [StevenBaby/onix#3]
https://github.com/StevenBaby/onix/blob/748013c6ace822c0034c95291c41e0033f24c1bd/src/include/onix/types.h#L28

1、应该使用  typedef signed char  int8;   因为  char 的符号类型标准未明确，取决于编译器实现。
2、如何判断出 int 就是 int32 而 long long 就是 int64，之前看有 LP32、LP64这些，如果自己写话要如何精确定义。
ref:
https://zh.cppreference.com/w/cpp/language/types
https://www.ibm.com/docs/en/zos/2.1.0?topic=options-lp64-ilp32

**Comment by StevenBaby** [comment]
一般来说，需要对特殊的机器，特殊定义，会有很多 #ifdef xxx 来作多平台兼容。
