### ISSUE TITLE
cat keyboard后卡死

### ISSUE THREAD

**Issue by noahze01** [StevenBaby/onix#38]
cat函数有问题
![image](https://github.com/StevenBaby/onix/assets/141596824/ca7786b7-905e-4c80-8009-55a12f004429)

**Comment by orengeokami** [comment]
cat程序中读取CHRDEV时会传入读取大小1024Bytes，在keyboard fifo没有这么多数据时任务会进入阻塞状态，如果想要看到现象，敲1024个:) ...最简单的方法就是把读取大小改为1Byte，或者实现传入读取一次无论长度是否满足都立即返回的标志的功能后，在VFS READ或者TTY READ里加上Read标志就可以实现。
