### ISSUE TITLE
关于arena.cc文件里面的kfree函数，某些函数编码顺序应该调整调整一下

### ISSUE THREAD

**Issue by LunarStore** [StevenBaby/onix#41]
arena.cc文件里面的kfree函数中：
free_kpage((u32)arena, 1);函数应该在
arena->desc->page_count--;
assert(arena->desc->page_count >= BUF_COUNT);
后面调用，不然这属于典型的释放了内存，但继续引用这块内存，这样很危险！！！

**Comment by LunarStore** [comment]
后续如果拓展onix成多核的话，这个可能就是个潜在的bug。

**Comment by StevenBaby** [comment]
> 后续如果拓展onix成多核的话，这个可能就是个潜在的bug。

挪到后面，提个 pr 吧
