### ISSUE TITLE
ide硬盘分区扇区的lba计算是不是有点问题？

### ISSUE THREAD

**Issue by Ca1Ne93** [StevenBaby/onix#43]
device_request中idx_t offset = idx + device_ioctl(device->dev, DEV_CMD_SECTOR_START, 0, 0);计算了一遍lba，在ide_pio_part_write中，又加了一遍part->start。

**Comment by StevenBaby** [comment]
device_request 中不会使用 part 来读写，是读写整个磁盘的；

**Comment by Ca1Ne93** [comment]
好的，因为看到79的test测试，使用的是写part的方式，所以有此疑问。
