### ISSUE TITLE
识别硬盘获取的信息

### ISSUE THREAD

**Issue by vanJker** [StevenBaby/onix#51]
Onix 中将识别硬盘获得的数据的第 1、3、6 个 word 分别视为 cylinders, heads, sectors per track 信息，但是我查询了 [相关手册](https://tc.gts3.org/cs3210/2016/spring/r/hardware/ATA8-ACS.pdf) (硬盘识别数据说明部分位于 7.16.7) ，里面对这些 word 的说明是 Obsolete 即这些数据是无效信息。想请教一下作者参考的资料？

**Comment by 1031507008** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by StevenBaby** [comment]
表应该是 7.17.7 吧，这里具体实现主要参考了 [sanos](https://github.com/ringgaard/sanos) ，CHS 这几个参数，在实践过程中没有用到，所以实际上无关紧要，只用到了 LBA 模式。
