### ISSUE TITLE
将内核代码放到 0x6efffff 之后，printk 传递的字符串常量用指针取出来是空的。

### ISSUE THREAD

**Issue by SoulSubmerge** [StevenBaby/onix#53]
大佬好，我在哔哩哔哩看到UP主的视频，我将内核代码放到 0x6efffff 之后，printk 传递的字符串常量用指针取出来是空的，bochs 的内存我设置了 512MB，可以请教一下这是什么原因吗？

**Comment by StevenBaby** [comment]
1. 在内核代码加载完成之后，检查对应内存是否已经修改为内核文件内容（最新代码通过 elftools/crc32 校验内核完整性）；
2. 确认代码编译的地址是正确的或者是位置无关的代码（目前未实现）；
3. 必要时，打断点检测常量指针和传入参数的栈内存的变化；
4. 建议，如非必要，不要修改项目代码，或者只做小修改，观察变化，等真正理解之后再做优化，这样可以节约很多调试的时间（当然踩坑也是一种成长，看你的取舍）；

**Comment by SoulSubmerge** [comment]
> 1. 在内核代码加载完成之后，检查对应内存是否已经修改为内核文件内容（最新代码通过 elftools/crc32 校验内核完整性）；
> 2. 确认代码编译的地址是正确的或者是位置无关的代码（目前未实现）；
> 3. 必要时，打断点检测常量指针和传入参数的栈内存的变化；
> 4. 建议，如非必要，不要修改项目代码，或者只做小修改，观察变化，等真正理解之后再做优化，这样可以节约很多调试的时间（当然踩坑也是一种成长，看你的取舍）；

感谢大佬的回答，我发现我忘记修改链接的入口点地址了，非常感谢大佬。
