### ISSUE TITLE
使用__atrribute__((packed)) 报错

### ISSUE THREAD

**Issue by wulongdog** [StevenBaby/onix#9]
在做全局描述符表时，使用__atrribute__((packed)) 会报错

src/include/onix/global.h:22:17: error: expected declaration specifiers or ‘...’ before ‘(’ token
   22 | } __atrribute__((packed)) descriptor_t;

gcc 版本
gcc (Ubuntu 11.1.0-1ubuntu1~18.04.1) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by echoechoin** [comment]
chatgpt给你回答了：

这个错误提示表明在代码的第22行中，有一个拼写错误：`attribute` 被拼写成了` atrribute`，因此编译器无法识别 `atrribute`，从而导致错误。请将代码中的 `atrribute` 改为 `attribute`，应该就能解决这个问题。

正确的代码应该是：

```c
} __attribute__((packed)) descriptor_t;
```
请注意，这里使用了双下划线来括起 attribute，这是因为 attribute 是一个GCC扩展，为了避免与C++标准库中的名称冲突，GCC使用了这种命名约定。

**Comment by StevenBaby** [comment]
好好学英语，很重要啊！😉

**Comment by wulongdog** [comment]
> chatgpt给你回答了：
> 
> 这个错误提示表明在代码的第22行中，有一个拼写错误：`attribute` 被拼写成了` atrribute`，因此编译器无法识别 `atrribute`，从而导致错误。请将代码中的 `atrribute` 改为 `attribute`，应该就能解决这个问题。
> 
> 正确的代码应该是：
> 
> ```c
> } __attribute__((packed)) descriptor_t;
> ```
> 
> 请注意，这里使用了双下划线来括起 attribute，这是因为 attribute 是一个GCC扩展，为了避免与C++标准库中的名称冲突，GCC使用了这种命名约定。

谢谢你~

**Comment by wulongdog** [comment]
> 好好学英语，很重要啊！😉

好的好的,听从大佬的忠告 💖
